version: "3.5"
services:
  db:
    image: 'postgres:13'
    container_name: 'db'
    networks:
      - backend
    env_file: ./env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  my_social_network:
    build: .
    container_name: 'my_social_network'
    image: 'my_social_network:1'
    command: >
      sh -c 'cd src &&
             poetry run python3 manage.py migrate --no-input &&
             poetry run python3 manage.py createadmin &&
             poetry run python3 manage.py collectstatic --noinput &&
             poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8080 '
    networks:
      - backend
    volumes:
      - ./src:/service/src
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.app.env
      - ./env/.server_1.env
    restart: unless-stopped
    depends_on:
      - db

  web_server:
    image: 'nginx:alpine3.18'
    container_name: 'web_server'
    networks:
      - backend
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf
      - app_static:/srv/static
      - app_media:/srv/media
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - my_social_network

networks:
  backend:

volumes:
  postgres_data:
  app_static:
  app_media:
  grafana_data:
  grafana_configs:
  prometheus_data:
  prometheus_configs:
