# Generated by Django 4.2.4 on 2023-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
