# Generated by Django 4.2.4 on 2023-09-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_reply_options_alter_likecontract_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
