# Generated by Django 4.2.4 on 2023-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_gender_alter_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(max_length=120, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/photos/%Y/%m/%h/', verbose_name='Avatar'),
        ),
    ]
