# Generated by Django 4.2.4 on 2023-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_description_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
