# Generated by Django 4.2.4 on 2023-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_contract_account_followings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/cover/%Y/%m/%d/'),
        ),
    ]
