# Generated by Django 4.2.4 on 2023-09-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='FollowContract',
        ),
        migrations.RenameIndex(
            model_name='followcontract',
            new_name='account_fol_created_745bd6_idx',
            old_name='account_con_created_8c552f_idx',
        ),
    ]
